/**
 * Proposed JSON Schemas for GameBus property templates (admin migration).
 * ACTIVITY payload uses shape B: { template, obj: { value: <schema value> } }.
 */
export const STUDENT_LUNCH_CHECKIN_PROPERTY_SCHEMAS = {
  targetDate: {
    reference: 'targetDate',
    displayName: 'Target date',
    activityLinkRequired: true,
    schema: { type: 'string', format: 'date' },
    example: { value: '2026-07-29' },
  },
  mealType: {
    reference: 'mealType',
    displayName: 'Meal type',
    activityLinkRequired: true,
    schema: { type: 'string', enum: ['regular', 'soup', 'no_lunch'] },
    example: { value: 'regular' },
  },
  mainItemId: {
    reference: 'mainItemId',
    displayName: 'Main dish id',
    activityLinkRequired: false,
    schema: { type: 'string', minLength: 1 },
    example: { value: 'chicken-steak-with-pesto-sauce-and-pasta' },
  },
  mainQuantity: {
    reference: 'mainQuantity',
    displayName: 'Main quantity',
    activityLinkRequired: true,
    schema: { type: 'integer', minimum: 0, maximum: 6 },
    example: { value: 2 },
  },
  vegetarianItemId: {
    reference: 'vegetarianItemId',
    displayName: 'Vegetarian dish id',
    activityLinkRequired: false,
    schema: { type: 'string', minLength: 1 },
    example: { value: 'chickpea-and-apricot-stew-with-pasta' },
  },
  vegetarianQuantity: {
    reference: 'vegetarianQuantity',
    displayName: 'Vegetarian quantity',
    activityLinkRequired: true,
    schema: { type: 'integer', minimum: 0, maximum: 6 },
    example: { value: 0 },
  },
  soupItemId: {
    reference: 'soupItemId',
    displayName: 'Soup id',
    activityLinkRequired: false,
    schema: { type: 'string', minLength: 1 },
    example: { value: 'pike-fish-ball-soup' },
  },
  soupQuantity: {
    reference: 'soupQuantity',
    displayName: 'Soup quantity',
    activityLinkRequired: true,
    schema: { type: 'integer', minimum: 0, maximum: 6 },
    example: { value: 1 },
  },
  dessertItemId: {
    reference: 'dessertItemId',
    displayName: 'Dessert id',
    activityLinkRequired: false,
    schema: { type: 'string', minLength: 1 },
    example: { value: 'mango-and-pear-lassi' },
  },
  dessertQuantity: {
    reference: 'dessertQuantity',
    displayName: 'Dessert quantity',
    activityLinkRequired: true,
    schema: { type: 'integer', minimum: 0, maximum: 6 },
    example: { value: 0 },
  },
  timingStatus: {
    reference: 'timingStatus',
    displayName: 'Timing status',
    activityLinkRequired: true,
    schema: { type: 'string', enum: ['on-time', 'late'] },
    example: { value: 'on-time' },
  },
  submittedAt: {
    reference: 'submittedAt',
    displayName: 'Submitted at',
    activityLinkRequired: true,
    schema: { type: 'string', format: 'date-time' },
    example: { value: '2026-07-28T12:00:00.000Z' },
  },
} as const;

const INTEGER_SCHEMA_0_1000 = {
  type: 'integer',
  minimum: 0,
  maximum: 1000,
} as const;

const ITEM_ID_SCHEMA = { type: 'string', minLength: 1 } as const;

/** Proposed JSON Schemas for chefForecast property templates (admin migration). */
export const CHEF_FORECAST_PROPERTY_SCHEMAS = {
  targetDate: {
    reference: 'targetDate',
    displayName: 'Target date',
    exists: true,
    action: 'reuse',
    activityLinkRequired: true,
    schema: { type: 'string', format: 'date' },
    example: { value: '2026-07-29' },
    oldLinkedProperty: 'targetDate — retain',
  },
  forecastTotalCustomers: {
    reference: 'forecastTotalCustomers',
    displayName: 'Forecast total customers',
    exists: true,
    action: 'reuse',
    activityLinkRequired: true,
    schema: INTEGER_SCHEMA_0_1000,
    example: { value: 120 },
    oldLinkedProperty: 'forecastTotalCustomers — retain',
  },
  mainItemId: {
    reference: 'mainItemId',
    displayName: 'Main dish id',
    exists: true,
    action: 'reuse',
    activityLinkRequired: true,
    schema: ITEM_ID_SCHEMA,
    example: { value: 'chicken-steak-with-pesto-sauce-and-pasta' },
    oldLinkedProperty: 'none on chefForecast — reuse global template from studentLunchCheckin migration',
  },
  forecastMeat: {
    reference: 'forecastMeat',
    displayName: 'Forecast main (meat/classic)',
    exists: true,
    action: 'reuse',
    activityLinkRequired: true,
    schema: INTEGER_SCHEMA_0_1000,
    example: { value: 50 },
    oldLinkedProperty: 'forecastMeat — retain (maps to main forecast quantity)',
  },
  vegetarianItemId: {
    reference: 'vegetarianItemId',
    displayName: 'Vegetarian dish id',
    exists: true,
    action: 'reuse',
    activityLinkRequired: true,
    schema: ITEM_ID_SCHEMA,
    example: { value: 'chickpea-and-apricot-stew-with-pasta' },
    oldLinkedProperty: 'none on chefForecast — reuse global template',
  },
  forecastVegetarian: {
    reference: 'forecastVegetarian',
    displayName: 'Forecast vegetarian',
    exists: true,
    action: 'reuse',
    activityLinkRequired: true,
    schema: INTEGER_SCHEMA_0_1000,
    example: { value: 30 },
    oldLinkedProperty: 'forecastVegetarian — retain',
  },
  soupItemId: {
    reference: 'soupItemId',
    displayName: 'Soup id',
    exists: true,
    action: 'reuse',
    activityLinkRequired: true,
    schema: ITEM_ID_SCHEMA,
    example: { value: 'pike-fish-ball-soup' },
    oldLinkedProperty: 'none on chefForecast — reuse global template',
  },
  forecastSoup: {
    reference: 'forecastSoup',
    displayName: 'Forecast soup',
    exists: true,
    action: 'reuse',
    activityLinkRequired: true,
    schema: INTEGER_SCHEMA_0_1000,
    example: { value: 40 },
    oldLinkedProperty: 'forecastSoup — retain',
  },
  dessertItemId: {
    reference: 'dessertItemId',
    displayName: 'Dessert id',
    exists: true,
    action: 'reuse',
    activityLinkRequired: true,
    schema: ITEM_ID_SCHEMA,
    example: { value: 'mango-and-pear-lassi' },
    oldLinkedProperty: 'none on chefForecast — reuse global template',
  },
  forecastDessert: {
    reference: 'forecastDessert',
    displayName: 'Forecast dessert',
    exists: false,
    action: 'create',
    activityLinkRequired: true,
    schema: INTEGER_SCHEMA_0_1000,
    example: { value: 25 },
    oldLinkedProperty: 'none — new link required',
  },
  timingStatus: {
    reference: 'timingStatus',
    displayName: 'Timing status',
    exists: true,
    action: 'reuse',
    activityLinkRequired: true,
    schema: { type: 'string', enum: ['on-time', 'late'] },
    example: { value: 'on-time' },
    oldLinkedProperty: 'none on chefForecast — reuse global template',
  },
  submittedAt: {
    reference: 'submittedAt',
    displayName: 'Submitted at',
    exists: true,
    action: 'reuse',
    activityLinkRequired: true,
    schema: { type: 'string', format: 'date-time' },
    example: { value: '2026-07-28T12:00:00.000Z' },
    oldLinkedProperty: 'none on chefForecast — reuse global template (not currently linked)',
  },
  confidence: {
    reference: 'confidence',
    displayName: 'Confidence',
    exists: true,
    action: 'reuse',
    activityLinkRequired: false,
    schema: { type: 'number', minimum: 0, maximum: 1 },
    example: { value: 0.75 },
    oldLinkedProperty: 'confidence — keep linked on chefForecast (optional payload)',
  },
  notes: {
    reference: 'notes',
    displayName: 'Notes',
    exists: true,
    action: 'reuse',
    activityLinkRequired: false,
    schema: { type: 'string', minLength: 1 },
    example: { value: 'Staff shortage expected at lunch service.' },
    oldLinkedProperty: 'notes — keep linked on chefForecast (optional payload)',
  },
} as const;

/** Admin migration from live seven-property chefForecast to final fourteen-link template. */
export const CHEF_FORECAST_ADMIN_MIGRATION = [
  { current: 'targetDate', action: 'reuse', final: 'targetDate' },
  { current: 'forecastTotalCustomers', action: 'reuse', final: 'forecastTotalCustomers' },
  { current: 'forecastMeat', action: 'reuse', final: 'forecastMeat (main quantity)' },
  { current: 'forecastVegetarian', action: 'reuse', final: 'forecastVegetarian' },
  { current: 'forecastSoup', action: 'reuse', final: 'forecastSoup' },
  { current: 'confidence', action: 'keep linked', final: 'confidence (optional link)' },
  { current: 'notes', action: 'keep linked', final: 'notes (optional link)' },
  { current: null, action: 'add link', final: 'mainItemId' },
  { current: null, action: 'add link', final: 'vegetarianItemId' },
  { current: null, action: 'add link', final: 'soupItemId' },
  { current: null, action: 'add link', final: 'dessertItemId' },
  { current: null, action: 'create + link', final: 'forecastDessert' },
  { current: null, action: 'add link', final: 'timingStatus' },
  { current: null, action: 'add link', final: 'submittedAt' },
] as const;

/** Admin migration from live seven-property template to final twelve-property template. */
export const STUDENT_LUNCH_CHECKIN_ADMIN_MIGRATION = [
  { current: 'targetDate', action: 'reuse', final: 'targetDate' },
  { current: 'submittedAt', action: 'reuse', final: 'submittedAt' },
  { current: 'comingStatus', action: 'replace', final: 'mealType' },
  { current: 'selectedMain', action: 'replace', final: 'mainItemId + mainQuantity' },
  {
    current: 'selectedVegetarianOrNoVeg',
    action: 'replace',
    final: 'vegetarianItemId + vegetarianQuantity',
  },
  { current: 'selectedSoupOrNoSoup', action: 'replace', final: 'soupItemId + soupQuantity' },
  {
    current: 'selectedDessertOrNoDessert',
    action: 'replace',
    final: 'dessertItemId + dessertQuantity',
  },
  { current: null, action: 'add', final: 'timingStatus' },
] as const;
